<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WINDOWS-SBEN25R" failures="1" tests="12" name="Test" time="43.802" errors="0" timestamp="2025-03-31T13:51:46 IST">
  <testcase classname="api.testcases.UserTestDD" name="testCreateUser" time="3.229"/>
  <testcase classname="api.testcases.UserTestDD" name="testCreateUser" time="1.404"/>
  <testcase classname="api.testcases.UserTestDD" name="testCreateUser" time="1.25"/>
  <testcase classname="api.testcases.UserTestDD" name="testCreateUser" time="1.596"/>
  <testcase classname="api.testcases.UserTestDD" name="testGetUserData" time="6.623"/>
  <testcase classname="api.testcases.UserTestDD" name="testGetUserData" time="6.656"/>
  <testcase classname="api.testcases.UserTestDD" name="testGetUserData" time="6.367"/>
  <testcase classname="api.testcases.UserTestDD" name="testGetUserData" time="8.234"/>
  <testcase classname="api.testcases.UserTestDD" name="testDeletetUser" time="1.441"/>
  <testcase classname="api.testcases.UserTestDD" name="testDeletetUser" time="1.13"/>
  <testcase classname="api.testcases.UserTestDD" name="testDeletetUser" time="1.442">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.testcases.UserTestDD.testDeletetUser(UserTestDD.java:148)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeletetUser -->
  <testcase classname="api.testcases.UserTestDD" name="testDeletetUser" time="1.523"/>
</testsuite> <!-- Test -->
